title: KittikJS - create your own ASCII presentation in the terminal
description: KittikJS is an engine, written entirely with NodeJS, which is primary goal is to simplify building and showing ASCII presentations in the terminal
keywords: kittik, kittikjs, ascii, terminal, presentation, keynote, nodejs, node, javascript, js
url: http://kittikjs.com
